/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\dragon.gltf
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shenron-dragon-ball-96e8ad1e206941ce859c5733bec75d30
Title: Shenron (Dragon Ball)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF("/dragon.gltf");
  return (
    <group {...props} dispose={null} scale={0.0036}>
      <group position={[-5.59, 5.54, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Shenron_Green_0.geometry}
          material={materials.Green}
        />
        <mesh
          geometry={nodes.Shenron_Yellow_0.geometry}
          material={materials.Yellow}
        />
        <mesh
          geometry={nodes["Shenron_09_-_Default_0"].geometry}
          material={materials["09_-_Default"]}
        />
        <mesh
          geometry={nodes["Shenron_08_-_Default_0"].geometry}
          material={materials["08_-_Default"]}
        />
      </group>
      <group
        position={[2.81, 0, -0.39]}
        rotation={[-Math.PI / 3, 0, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes["One_Star_02_-_Default_0"].geometry}
          material={materials["02_-_Default"]}
        />
        <mesh
          geometry={nodes["One_Star_03_-_Default_0"].geometry}
          material={materials["03_-_Default"]}
        />
      </group>
      <group
        position={[11.79, 0, 13.47]}
        rotation={[-Math.PI / 3, 0, 0]}
        scale={0.05}
      >
        <group position={[-194.57, 249.78, -144.21]}>
          <mesh
            geometry={nodes["Four_Star_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
          <mesh
            geometry={nodes["Four_Star_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
          />
        </group>
      </group>
      <group
        position={[-4.43, 0, 13.21]}
        rotation={[-Math.PI / 3, 0, 0]}
        scale={0.05}
      >
        <group position={[141.75, 245.13, -141.52]}>
          <mesh
            geometry={nodes["Two_Star_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
          <mesh
            geometry={nodes["Two_Star_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
          />
        </group>
      </group>
      <group
        position={[-11.52, 0, -0.55]}
        rotation={[-Math.PI / 3, 0, 0]}
        scale={0.05}
      >
        <group position={[288.76, -2.09, 1.2]}>
          <mesh
            geometry={nodes["Five_Star_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
          <mesh
            geometry={nodes["Five_Star_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
          />
        </group>
      </group>
      <group
        position={[-5.82, 0, -14.26]}
        rotation={[-Math.PI / 3, 0, 0]}
        scale={0.05}
      >
        <group position={[170.59, -248.32, 143.37]}>
          <mesh
            geometry={nodes["Seven_Star_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
          <mesh
            geometry={nodes["Seven_Star_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
          />
        </group>
      </group>
      <group
        position={[11.55, 0, -13.89]}
        rotation={[-Math.PI / 3, 0, 0]}
        scale={0.05}
      >
        <group position={[-189.55, -241.63, 139.51]}>
          <mesh
            geometry={nodes["Star_Three_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
          <mesh
            geometry={nodes["Star_Three_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
          />
        </group>
      </group>
      <group
        position={[17.14, 0, -0.6]}
        rotation={[-Math.PI / 3, 0, 0]}
        scale={0.05}
      >
        <group position={[-305.55, -3.09, 1.78]}>
          <mesh
            geometry={nodes["Six_Star_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
          <mesh
            geometry={nodes["Six_Star_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/dragon.gltf");
